context:
  version: "0.1.23"

package:
  name: idt
  version: ${{ version }}

source:
  url: https://github.com/sh-cho/idt/archive/refs/tags/${{ version }}.tar.gz
  sha256: 79404c0aef153f350d2c2982641f42bc881fc597e58f92024382ee9f8c528cc4

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --no-track --locked --bins --root "$PREFIX" --path .
          # generate shell completions and manpage
          - mkdir -p "$PREFIX/share/bash-completion/completions" "$PREFIX/share/fish/vendor_completions.d" "$PREFIX/share/zsh/site-functions" "$PREFIX/share/man/man1"
          - '"$PREFIX/bin/idt" completions bash > "$PREFIX/share/bash-completion/completions/idt"'
          - '"$PREFIX/bin/idt" completions fish > "$PREFIX/share/fish/vendor_completions.d/idt.fish"'
          - '"$PREFIX/bin/idt" completions zsh  > "$PREFIX/share/zsh/site-functions/_idt"'
          - '"$PREFIX/bin/idt" manpage            "$PREFIX/share/man/man1"'
        else:
          - cargo auditable install --no-track --locked --bins --root "%LIBRARY_PREFIX%" --path .
          # generate shell completions and manpage
          - mkdir "%LIBRARY_PREFIX%\share\bash-completion\completions"
          - mkdir "%LIBRARY_PREFIX%\share\fish\vendor_completions.d"
          - mkdir "%LIBRARY_PREFIX%\share\zsh\site-functions"
          - mkdir "%LIBRARY_PREFIX%\share\man\man1"
          - '"%LIBRARY_BIN%\idt.exe" completions bash > "%LIBRARY_PREFIX%\share\bash-completion\completions\idt"'
          - '"%LIBRARY_BIN%\idt.exe" completions fish > "%LIBRARY_PREFIX%\share\fish\vendor_completions.d\idt.fish"'
          - '"%LIBRARY_BIN%\idt.exe" completions zsh  > "%LIBRARY_PREFIX%\share\zsh\site-functions\_idt"'
          - '"%LIBRARY_BIN%\idt.exe" manpage            "%LIBRARY_PREFIX%\share\man\man1"'
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - idt --help
      - idt --version
  - package_contents:
      bin:
        - idt
      files:
        - if: unix
          then:
            - share/bash-completion/completions/idt
            - share/fish/vendor_completions.d/idt.fish
            - share/zsh/site-functions/_idt
            - share/man/man1/idt.1
            - share/man/man1/idt-compare.1
            - share/man/man1/idt-completions.1
            - share/man/man1/idt-convert.1
            - share/man/man1/idt-gen.1
            - share/man/man1/idt-info.1
            - share/man/man1/idt-inspect.1
            - share/man/man1/idt-manpage.1
            - share/man/man1/idt-sort.1
            - share/man/man1/idt-validate.1
        - if: win
          then:
            - Library/share/bash-completion/completions/idt
            - Library/share/fish/vendor_completions.d/idt.fish
            - Library/share/zsh/site-functions/_idt
            - Library/share/man/man1/idt.1
            - Library/share/man/man1/idt-compare.1
            - Library/share/man/man1/idt-completions.1
            - Library/share/man/man1/idt-convert.1
            - Library/share/man/man1/idt-gen.1
            - Library/share/man/man1/idt-info.1
            - Library/share/man/man1/idt-inspect.1
            - Library/share/man/man1/idt-manpage.1
            - Library/share/man/man1/idt-sort.1
            - Library/share/man/man1/idt-validate.1
      strict: true

about:
  homepage: https://github.com/sh-cho/idt
  summary: A fast, ergonomic CLI tool for working with various ID formats
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://sh-cho.github.io/idt
  repository: https://github.com/sh-cho/idt

extra:
  recipe-maintainers:
    - salim-b
